name: cutcam
description: "AI-powered, offline haircut assistant."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # These must be active (no # symbol)
  camera: any
  tflite_flutter: any
  image: any
  shared_preferences: ^2.3.2
  flutter_tts: ^3.8.3

  # NEW PACKAGES FOR UPDATES:
  http: ^1.2.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.5
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/